### ISSUE TITLE
Display name for servers

### ISSUE THREAD

**Issue by Askarionn** [GemstoneGG/Velocity-CTD#322]
### Requested Feature

Would be cool to add display name for servers, something like this:
survival = { address = "127.0.0.1:30068", forwarding-mode = "MODERN" , display-name = "<red>Survival Earth"}

### Why is this needed?

messages

### Alternative Solutions

-

**Comment by R00tB33rMan** [comment]
> ### Requested Feature
> 
> Would be cool to add display name for servers, something like this: survival = { address = "127.0.0.1:30068", forwarding-mode = "MODERN" , display-name = "Survival Earth"}
> ### Why is this needed?
> 
> messages
> ### Alternative Solutions
> 
> 
> ### Additional Information
> 
> _No response_

I do understand the purpose of this; however, I feel it is best to brand the instance cohesively rather than having a display name override that can be misleading for users, on top of various other complications/issues that may arise in conjunction with this request. Additionally, this particular section in the configuration is designed for forced hosts, which doesn't align with the actual branding of the server and is instead used to map the correct forwarding type of the bound server.
